### ISSUE TITLE
Passing as a move

### ISSUE THREAD

**Issue by paddyooo** [stefanpeidli/GoNet#16]
Implementing passing as the 82nd possible move will make it possible for the network to learn when to pass. This doesnt necessarily improve the GO playing, because passing a lot doesnt really help winning.

**Comment by stefanpeidli** [comment]
Great! I will soon modify the network to also handle passing as (input and) output!

**Comment by paddyooo** [comment]
done! 
please leave it possible to use the network with 81 vector entries/ the old "passing" too :)
